// Dev-only generator for the U.S. Map chart type.
//
// Reads U.S. Census cartographic boundaries (us-atlas), simplifies them, projects
// with d3-geo AlbersUSA (which insets Alaska + Hawaii), and writes two committed,
// inlined data modules so the app ships with NO runtime map dependency:
//   src/usMapData.ts  — nation outline + interior state borders + viewBox
//   src/locations.ts  — the location picker list, CONUS/AK/HI projected to map space
//
// Run manually after changing the map resolution or scripts/locations.source.json:
//   node scripts/gen-usmap.mjs
//
// Deps (devDependencies only): us-atlas, d3-geo, topojson-client, topojson-simplify.

import { geoAlbersUsa, geoPath } from 'd3-geo'
import { feature, mesh } from 'topojson-client'
import { presimplify, simplify } from 'topojson-simplify'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '..')
const W = 960
const H = 600
// Simplification weight: larger drops more detail. Tuned so the nation path lands
// near ~19KB with no visible loss at display size.
const MIN_WEIGHT = 0.02

const round1 = (d) => d.replace(/-?\d+\.\d+/g, (n) => (+n).toFixed(1))

const topo = JSON.parse(readFileSync(resolve(ROOT, 'node_modules/us-atlas/states-10m.json'), 'utf8'))
const simplified = simplify(presimplify(topo), MIN_WEIGHT)

const nation = feature(simplified, simplified.objects.nation)
const borders = mesh(simplified, simplified.objects.states, (a, b) => a !== b)

const projection = geoAlbersUsa().fitSize([W, H], nation)
const path = geoPath(projection)
const nationPath = round1(path(nation))
const bordersPath = round1(path(borders))

// Project the location list.
const src = JSON.parse(readFileSync(resolve(HERE, 'locations.source.json'), 'utf8'))
const locations = []
for (const c of src.conus) {
  const p = projection([c.lon, c.lat])
  if (!p) {
    console.warn(`WARN: ${c.name} did not project (outside US); skipping geo`)
    locations.push({ id: c.id, name: c.name })
    continue
  }
  locations.push({ id: c.id, name: c.name, geo: { x: Math.round(p[0]), y: Math.round(p[1]) } })
}
for (const o of src.oconus) locations.push({ id: o.id, name: o.name, oconus: true })

const banner = '// AUTO-GENERATED by scripts/gen-usmap.mjs. Do not edit by hand.\n'

writeFileSync(
  resolve(ROOT, 'src/usMapData.ts'),
  banner +
    '\n/** Inlined U.S. map geometry (Census boundaries via us-atlas, AlbersUSA' +
    ' projection). All coordinates live in the viewBox space below. */\n' +
    'export const US_MAP = {\n' +
    `  viewBox: '0 0 ${W} ${H}',\n` +
    `  width: ${W},\n` +
    `  height: ${H},\n` +
    `  nation: '${nationPath}',\n` +
    `  borders: '${bordersPath}',\n` +
    '} as const\n',
)

writeFileSync(
  resolve(ROOT, 'src/locations.ts'),
  banner +
    '\n/** A pickable work location. CONUS/AK/HI carry projected map coordinates;\n' +
    ' *  overseas entries have no `geo` and render in the OCONUS strip. */\n' +
    'export interface MapLocation {\n' +
    '  id: string\n' +
    '  name: string\n' +
    '  geo?: { x: number; y: number }\n' +
    '  oconus?: boolean\n' +
    '}\n\n' +
    'export const LOCATIONS: MapLocation[] = ' +
    JSON.stringify(locations, null, 2) +
    '\n',
)

console.log(`nation: ${nationPath.length} chars | borders: ${bordersPath.length} chars`)
console.log(`locations: ${locations.length} (${locations.filter((l) => l.geo).length} on-map, ${locations.filter((l) => l.oconus).length} OCONUS)`)
