// AUTO-GENERATED by scripts/gen-usmap.mjs. Do not edit by hand.

/** A pickable work location. CONUS/AK/HI carry projected map coordinates;
 *  overseas entries have no `geo` and render in the OCONUS strip. */
export interface MapLocation {
  id: string
  name: string
  geo?: { x: number; y: number }
  oconus?: boolean
}

export const LOCATIONS: MapLocation[] = [
  {
    "id": "washington-dc",
    "name": "Washington, DC",
    "geo": {
      "x": 837,
      "y": 260
    }
  },
  {
    "id": "arlington-va",
    "name": "Arlington, VA",
    "geo": {
      "x": 836,
      "y": 261
    }
  },
  {
    "id": "fort-belvoir-va",
    "name": "Fort Belvoir, VA",
    "geo": {
      "x": 836,
      "y": 264
    }
  },
  {
    "id": "fort-meade-md",
    "name": "Fort Meade, MD",
    "geo": {
      "x": 841,
      "y": 255
    }
  },
  {
    "id": "quantico-va",
    "name": "Quantico, VA",
    "geo": {
      "x": 835,
      "y": 269
    }
  },
  {
    "id": "aberdeen-md",
    "name": "Aberdeen, MD",
    "geo": {
      "x": 850,
      "y": 245
    }
  },
  {
    "id": "norfolk-va",
    "name": "Norfolk, VA",
    "geo": {
      "x": 859,
      "y": 301
    }
  },
  {
    "id": "newport-news-va",
    "name": "Newport News, VA",
    "geo": {
      "x": 855,
      "y": 297
    }
  },
  {
    "id": "huntsville-al",
    "name": "Huntsville, AL",
    "geo": {
      "x": 690,
      "y": 374
    }
  },
  {
    "id": "montgomery-al",
    "name": "Montgomery, AL",
    "geo": {
      "x": 700,
      "y": 424
    }
  },
  {
    "id": "warner-robins-ga",
    "name": "Warner Robins, GA",
    "geo": {
      "x": 748,
      "y": 413
    }
  },
  {
    "id": "atlanta-ga",
    "name": "Atlanta, GA",
    "geo": {
      "x": 731,
      "y": 390
    }
  },
  {
    "id": "orlando-fl",
    "name": "Orlando, FL",
    "geo": {
      "x": 801,
      "y": 494
    }
  },
  {
    "id": "tampa-fl",
    "name": "Tampa, FL",
    "geo": {
      "x": 783,
      "y": 509
    }
  },
  {
    "id": "pensacola-fl",
    "name": "Pensacola, FL",
    "geo": {
      "x": 688,
      "y": 467
    }
  },
  {
    "id": "jacksonville-fl",
    "name": "Jacksonville, FL",
    "geo": {
      "x": 790,
      "y": 457
    }
  },
  {
    "id": "charleston-sc",
    "name": "Charleston, SC",
    "geo": {
      "x": 813,
      "y": 400
    }
  },
  {
    "id": "fayetteville-nc",
    "name": "Fayetteville, NC",
    "geo": {
      "x": 822,
      "y": 348
    }
  },
  {
    "id": "dayton-oh",
    "name": "Dayton, OH",
    "geo": {
      "x": 718,
      "y": 261
    }
  },
  {
    "id": "rome-ny",
    "name": "Rome, NY",
    "geo": {
      "x": 843,
      "y": 164
    }
  },
  {
    "id": "boston-ma",
    "name": "Boston, MA",
    "geo": {
      "x": 914,
      "y": 165
    }
  },
  {
    "id": "lexington-ma",
    "name": "Lexington, MA",
    "geo": {
      "x": 911,
      "y": 164
    }
  },
  {
    "id": "philadelphia-pa",
    "name": "Philadelphia, PA",
    "geo": {
      "x": 863,
      "y": 231
    }
  },
  {
    "id": "new-york-ny",
    "name": "New York, NY",
    "geo": {
      "x": 877,
      "y": 211
    }
  },
  {
    "id": "chicago-il",
    "name": "Chicago, IL",
    "geo": {
      "x": 658,
      "y": 221
    }
  },
  {
    "id": "st-louis-mo",
    "name": "St. Louis, MO",
    "geo": {
      "x": 622,
      "y": 294
    }
  },
  {
    "id": "omaha-ne",
    "name": "Omaha, NE",
    "geo": {
      "x": 527,
      "y": 240
    }
  },
  {
    "id": "oklahoma-city-ok",
    "name": "Oklahoma City, OK",
    "geo": {
      "x": 499,
      "y": 366
    }
  },
  {
    "id": "san-antonio-tx",
    "name": "San Antonio, TX",
    "geo": {
      "x": 479,
      "y": 496
    }
  },
  {
    "id": "fort-worth-tx",
    "name": "Fort Worth, TX",
    "geo": {
      "x": 502,
      "y": 424
    }
  },
  {
    "id": "houston-tx",
    "name": "Houston, TX",
    "geo": {
      "x": 537,
      "y": 489
    }
  },
  {
    "id": "colorado-springs-co",
    "name": "Colorado Springs, CO",
    "geo": {
      "x": 380,
      "y": 286
    }
  },
  {
    "id": "denver-co",
    "name": "Denver, CO",
    "geo": {
      "x": 379,
      "y": 266
    }
  },
  {
    "id": "albuquerque-nm",
    "name": "Albuquerque, NM",
    "geo": {
      "x": 341,
      "y": 364
    }
  },
  {
    "id": "ogden-ut",
    "name": "Ogden, UT",
    "geo": {
      "x": 271,
      "y": 220
    }
  },
  {
    "id": "salt-lake-city-ut",
    "name": "Salt Lake City, UT",
    "geo": {
      "x": 271,
      "y": 230
    }
  },
  {
    "id": "tucson-az",
    "name": "Tucson, AZ",
    "geo": {
      "x": 256,
      "y": 415
    }
  },
  {
    "id": "las-vegas-nv",
    "name": "Las Vegas, NV",
    "geo": {
      "x": 199,
      "y": 318
    }
  },
  {
    "id": "los-angeles-ca",
    "name": "Los Angeles, CA",
    "geo": {
      "x": 137,
      "y": 351
    }
  },
  {
    "id": "san-diego-ca",
    "name": "San Diego, CA",
    "geo": {
      "x": 149,
      "y": 383
    }
  },
  {
    "id": "sacramento-ca",
    "name": "Sacramento, CA",
    "geo": {
      "x": 107,
      "y": 242
    }
  },
  {
    "id": "seattle-wa",
    "name": "Seattle, WA",
    "geo": {
      "x": 147,
      "y": 51
    }
  },
  {
    "id": "portland-or",
    "name": "Portland, OR",
    "geo": {
      "x": 130,
      "y": 93
    }
  },
  {
    "id": "anchorage-ak",
    "name": "Anchorage, AK",
    "geo": {
      "x": 161,
      "y": 522
    }
  },
  {
    "id": "fairbanks-ak",
    "name": "Fairbanks, AK",
    "geo": {
      "x": 166,
      "y": 494
    }
  },
  {
    "id": "honolulu-hi",
    "name": "Honolulu, HI",
    "geo": {
      "x": 307,
      "y": 527
    }
  },
  {
    "id": "ramstein-de",
    "name": "Ramstein, Germany",
    "oconus": true
  },
  {
    "id": "stuttgart-de",
    "name": "Stuttgart, Germany",
    "oconus": true
  },
  {
    "id": "kaiserslautern-de",
    "name": "Kaiserslautern, Germany",
    "oconus": true
  },
  {
    "id": "raf-lakenheath-uk",
    "name": "RAF Lakenheath, UK",
    "oconus": true
  },
  {
    "id": "aviano-it",
    "name": "Aviano, Italy",
    "oconus": true
  },
  {
    "id": "rota-es",
    "name": "Naval Station Rota, Spain",
    "oconus": true
  },
  {
    "id": "camp-humphreys-kr",
    "name": "Camp Humphreys, South Korea",
    "oconus": true
  },
  {
    "id": "yokota-jp",
    "name": "Yokota AB, Japan",
    "oconus": true
  },
  {
    "id": "kadena-jp",
    "name": "Kadena AB, Japan",
    "oconus": true
  },
  {
    "id": "andersen-gu",
    "name": "Andersen AFB, Guam",
    "oconus": true
  },
  {
    "id": "al-udeid-qa",
    "name": "Al Udeid, Qatar",
    "oconus": true
  },
  {
    "id": "nsa-bahrain",
    "name": "NSA Bahrain",
    "oconus": true
  },
  {
    "id": "camp-lemonnier-dj",
    "name": "Camp Lemonnier, Djibouti",
    "oconus": true
  },
  {
    "id": "diego-garcia",
    "name": "Diego Garcia",
    "oconus": true
  }
]
